services:
  scraper:
    build: app/.
    volumes:
        - /cross_vol:/app/data
  streamlit:
    build: streamlit/.
    depends_on:
      - scraper
    volumes:
      - /cross_vol:/streamlit/data
    ports: 
      - 8501:8501
volumes:
  cross_vol:
    external: true